include "hardware.inc"
include "consts.inc"

/*
============================
Constants
============================
*/

section "Discord Tiles", rom0
DiscordClient::
    incbin "gfx/discord.2bpp"
.end::

section "Discord Tilemap", rom0
DiscordClientTilemap::
    incbin "gfx/discord.tilemap"
.end::

section "Discord Logo Tiles", rom0
DiscordLogo::
    incbin "gfx/discord_logo.2bpp"
.end::

section "Discord Logo Tilemap", rom0
DiscordLogoTilemap::
    incbin "gfx/discord_logo.tilemap"
.end::

section "Dialog Tiles", rom0
Dialog::
    incbin "gfx/dialog-box.2bpp"
.end::

section "Dialog Tilemap", rom0
DialogTilemap::
    incbin "gfx/dialog-box.tilemap"
.end::

section "Sine Lookup Table", rom0, align [8]
SineLookupTable::
    def ANGLE = 0.0
    REPT 144
        db MUL(10, SIN(ANGLE))
        redef ANGLE = ANGLE + 1700.0
    ENDR
.end::

section "Font", rom0
opt bX.

; created with help from https://github.com/nezticle/rgbds-template/blob/master/inc/ibmpc1.inc
Font::
    db %........
    db %........
    db %........
    db %........
    db %........
    db %........
    db %........
    db %........

    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %........
    db %..XX....
    db %..XX....
    
    db %........
    db %.XX.XX..
    db %.XX.XX..
    db %........
    db %........
    db %........
    db %........
    db %........

    db %.XX.XX..
    db %.XX.XX..
    db %XXXXXXX.
    db %.XX.XX..
    db %.XX.XX..
    db %XXXXXXX.
    db %.XX.XX..
    db %.XX.XX..

    db %..XX....
    db %.XXXXX..
    db %XX......
    db %.XXXX...
    db %....XX..
    db %XXXXX...
    db %..XX....
    db %........

    db %........
    db %XX...XX.
    db %XX..XX..
    db %...XX...
    db %..XX....
    db %.XX..XX.
    db %XX...XX.
    db %........

    db %..XXX...
    db %.XX.XX..
    db %..XXX...
    db %.XXX.XX.
    db %XX.XXX..
    db %XX..XX..
    db %.XXX.XX.
    db %........

    db %.XX.....
    db %.XX.....
    db %XX......
    db %........
    db %........
    db %........
    db %........
    db %........

    db %...XX...
    db %..XX....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %..XX....
    db %...XX...
    db %........

    db %.XX.....
    db %..XX....
    db %...XX...
    db %...XX...
    db %...XX...
    db %..XX....
    db %.XX.....
    db %........

    db %........
    db %.XX..XX.
    db %..XXXX..
    db %XXXXXXXX & $FF
    db %..XXXX..
    db %.XX..XX.
    db %........
    db %........

    db %........
    db %..XX....
    db %..XX....
    db %XXXXXX..
    db %..XX....
    db %..XX....
    db %........
    db %........

    db %........
    db %........
    db %........
    db %........
    db %........
    db %..XX....
    db %..XX....
    db %.XX.....

    db %........
    db %........
    db %........
    db %XXXXXX..
    db %........
    db %........
    db %........
    db %........

    db %........
    db %........
    db %........
    db %........
    db %........
    db %..XX....
    db %..XX....
    db %........

    db %.....XX.
    db %....XX..
    db %...XX...
    db %..XX....
    db %.XX.....
    db %XX......
    db %X.......
    db %........

    db %.XXXXX..
    db %XX...XX.
    db %XX..XXX.
    db %XX.XXXX.
    db %XXXX.XX.
    db %XXX..XX.
    db %.XXXXX..
    db %........

    db %..XX....
    db %.XXX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %XXXXXX..
    db %........

    db %.XXXX...
    db %XX..XX..
    db %....XX..
    db %..XXX...
    db %.XX.....
    db %XX..XX..
    db %XXXXXX..
    db %........

    db %.XXXX...
    db %XX..XX..
    db %....XX..
    db %..XXX...
    db %....XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %...XXX..
    db %..XXXX..
    db %.XX.XX..
    db %XX..XX..
    db %XXXXXXX.
    db %....XX..
    db %...XXXX.
    db %........

    db %XXXXXX..
    db %XX......
    db %XXXXX...
    db %....XX..
    db %....XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %..XXX...
    db %.XX.....
    db %XX......
    db %XXXXX...
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %XXXXXX..
    db %XX..XX..
    db %....XX..
    db %...XX...
    db %..XX....
    db %..XX....
    db %..XX....
    db %........

    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %.XXXXX..
    db %....XX..
    db %...XX...
    db %.XXX....
    db %........

    db %........
    db %..XX....
    db %..XX....
    db %........
    db %........
    db %..XX....
    db %..XX....
    db %........

    db %........
    db %..XX....
    db %..XX....
    db %........
    db %........
    db %..XX....
    db %..XX....
    db %.XX.....

    db %...XX...
    db %..XX....
    db %.XX.....
    db %XX......
    db %.XX.....
    db %..XX....
    db %...XX...
    db %........

    db %........
    db %........
    db %XXXXXX..
    db %........
    db %........
    db %XXXXXX..
    db %........
    db %........

    db %.XX.....
    db %..XX....
    db %...XX...
    db %....XX..
    db %...XX...
    db %..XX....
    db %.XX.....
    db %........

    db %.XXXX...
    db %XX..XX..
    db %....XX..
    db %...XX...
    db %..XX....
    db %........
    db %..XX....
    db %........

    db %.XXXXX..
    db %XX...XX.
    db %XX.XXXX.
    db %XX.XXXX.
    db %XX.XXXX.
    db %XX......
    db %.XXXX...
    db %........

    db %..XX....
    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %XXXXXX..
    db %XX..XX..
    db %XX..XX..
    db %........

    db %XXXXXX..
    db %.XX..XX.
    db %.XX..XX.
    db %.XXXXX..
    db %.XX..XX.
    db %.XX..XX.
    db %XXXXXX..
    db %........

    db %..XXXX..
    db %.XX..XX.
    db %XX......
    db %XX......
    db %XX......
    db %.XX..XX.
    db %..XXXX..
    db %........

    db %XXXXX...
    db %.XX.XX..
    db %.XX..XX.
    db %.XX..XX.
    db %.XX..XX.
    db %.XX.XX..
    db %XXXXX...
    db %........

    db %.XXXXXX.
    db %.XX.....
    db %.XX.....
    db %.XXXX...
    db %.XX.....
    db %.XX.....
    db %.XXXXXX.
    db %........

    db %.XXXXXX.
    db %.XX.....
    db %.XX.....
    db %.XXXX...
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %........

    db %..XXXX..
    db %.XX..XX.
    db %XX......
    db %XX......
    db %XX..XXX.
    db %.XX..XX.
    db %..XXXXX.
    db %........

    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XXXXXX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %........

    db %.XXXX...
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %.XXXX...
    db %........

    db %...XXXX.
    db %....XX..
    db %....XX..
    db %....XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %XXX..XX.
    db %.XX..XX.
    db %.XX.XX..
    db %.XXXX...
    db %.XX.XX..
    db %.XX..XX.
    db %XXX..XX.
    db %........

    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XXXXXX.
    db %........

    db %XX...XX.
    db %XXX.XXX.
    db %XXXXXXX.
    db %XXXXXXX.
    db %XX.X.XX.
    db %XX...XX.
    db %XX...XX.
    db %........

    db %XX...XX.
    db %XXX..XX.
    db %XXXX.XX.
    db %XX.XXXX.
    db %XX..XXX.
    db %XX...XX.
    db %XX...XX.
    db %........

    db %..XXX...
    db %.XX.XX..
    db %XX...XX.
    db %XX...XX.
    db %XX...XX.
    db %.XX.XX..
    db %..XXX...
    db %........

    db %XXXXXX..
    db %.XX..XX.
    db %.XX..XX.
    db %.XXXXX..
    db %.XX.....
    db %.XX.....
    db %XXXX....
    db %........

    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX.XXX..
    db %.XXXX...
    db %...XXX..
    db %........

    db %XXXXXX..
    db %.XX..XX.
    db %.XX..XX.
    db %.XXXXX..
    db %.XX.XX..
    db %.XX..XX.
    db %XXX..XX.
    db %........

    db %.XXXX...
    db %XX..XX..
    db %XXX.....
    db %.XXXX...
    db %...XXX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %XXXXXX..
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %........

    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XXXXXX..
    db %........

    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %..XX....
    db %........

    db %XX...XX.
    db %XX...XX.
    db %XX...XX.
    db %XX.X.XX.
    db %XXXXXXX.
    db %XXX.XXX.
    db %XX...XX.
    db %........

    db %XX...XX.
    db %XX...XX.
    db %.XX.XX..
    db %..XXX...
    db %..XXX...
    db %.XX.XX..
    db %XX...XX.
    db %........

    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %..XX....
    db %..XX....
    db %.XXXX...
    db %........

    db %XXXXXXX.
    db %.....XX.
    db %....XX..
    db %...XX...
    db %..XX....
    db %.XX.....
    db %XXXXXXX.
    db %........

    db %.XXXX...
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XX.....
    db %.XXXX...
    db %........

    db %XX......
    db %.XX.....
    db %..XX....
    db %...XX...
    db %....XX..
    db %.....XX.
    db %......X.
    db %........

    db %.XXXX...
    db %...XX...
    db %...XX...
    db %...XX...
    db %...XX...
    db %...XX...
    db %.XXXX...
    db %........

    db %...X....
    db %..XXX...
    db %.XX.XX..
    db %XX...XX.
    db %........
    db %........
    db %........
    db %........

    db %........
    db %........
    db %........
    db %........
    db %........
    db %........
    db %........
    db %XXXXXXXX & $FF

    db %..XX....
    db %..XX....
    db %...XX...
    db %........
    db %........
    db %........
    db %........
    db %........

    db %........
    db %........
    db %.XXXX...
    db %....XX..
    db %.XXXXX..
    db %XX..XX..
    db %.XXX.XX.
    db %........

    db %XXX.....
    db %.XX.....
    db %.XX.....
    db %.XXXXX..
    db %.XX..XX.
    db %.XX..XX.
    db %XX.XXX..
    db %........

    db %........
    db %........
    db %.XXXX...
    db %XX..XX..
    db %XX......
    db %XX..XX..
    db %.XXXX...
    db %........

    db %...XXX..
    db %....XX..
    db %....XX..
    db %.XXXXX..
    db %XX..XX..
    db %XX..XX..
    db %.XXX.XX.
    db %........

    db %........
    db %........
    db %.XXXX...
    db %XX..XX..
    db %XXXXXX..
    db %XX......
    db %.XXXX...
    db %........

    db %..XXX...
    db %.XX.XX..
    db %.XX.....
    db %XXXX....
    db %.XX.....
    db %.XX.....
    db %XXXX....
    db %........

    db %........
    db %........
    db %.XXX.XX.
    db %XX..XX..
    db %XX..XX..
    db %.XXXXX..
    db %....XX..
    db %XXXXX...

    db %XXX.....
    db %.XX.....
    db %.XX.XX..
    db %.XXX.XX.
    db %.XX..XX.
    db %.XX..XX.
    db %XXX..XX.
    db %........

    db %..XX....
    db %........
    db %.XXX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %.XXXX...
    db %........

    db %....XX..
    db %........
    db %....XX..
    db %....XX..
    db %....XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...

    db %XXX.....
    db %.XX.....
    db %.XX..XX.
    db %.XX.XX..
    db %.XXXX...
    db %.XX.XX..
    db %XXX..XX.
    db %........

    db %.XXX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %..XX....
    db %.XXXX...
    db %........

    db %........
    db %........
    db %XX..XX..
    db %XXXXXXX.
    db %XXXXXXX.
    db %XX.X.XX.
    db %XX...XX.
    db %........

    db %........
    db %........
    db %XXXXX...
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %........

    db %........
    db %........
    db %.XXXX...
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %........

    db %........
    db %........
    db %XX.XXX..
    db %.XX..XX.
    db %.XX..XX.
    db %.XXXXX..
    db %.XX.....
    db %XXXX....

    db %........
    db %........
    db %.XXX.XX.
    db %XX..XX..
    db %XX..XX..
    db %.XXXXX..
    db %....XX..
    db %...XXXX.

    db %........
    db %........
    db %XX.XXX..
    db %.XXX.XX.
    db %.XX..XX.
    db %.XX.....
    db %XXXX....
    db %........

    db %........
    db %........
    db %.XXXXX..
    db %XX......
    db %.XXXX...
    db %....XX..
    db %XXXXX...
    db %........

    db %...X....
    db %..XX....
    db %.XXXXX..
    db %..XX....
    db %..XX....
    db %..XX.X..
    db %...XX...
    db %........

    db %........
    db %........
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXX.XX.
    db %........

    db %........
    db %........
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXX...
    db %..XX....
    db %........

    db %........
    db %........
    db %XX...XX.
    db %XX.X.XX.
    db %XXXXXXX.
    db %XXXXXXX.
    db %.XX.XX..
    db %........

    db %........
    db %........
    db %XX...XX.
    db %.XX.XX..
    db %..XXX...
    db %.XX.XX..
    db %XX...XX.
    db %........

    db %........
    db %........
    db %XX..XX..
    db %XX..XX..
    db %XX..XX..
    db %.XXXXX..
    db %....XX..
    db %XXXXX...

    db %........
    db %........
    db %XXXXXX..
    db %X..XX...
    db %..XX....
    db %.XX..X..
    db %XXXXXX..
    db %........

    db %...XXX..
    db %..XX....
    db %..XX....
    db %XXX.....
    db %..XX....
    db %..XX....
    db %...XXX..
    db %........

    db %...XX...
    db %...XX...
    db %...XX...
    db %........
    db %...XX...
    db %...XX...
    db %...XX...
    db %........

    db %XXX.....
    db %..XX....
    db %..XX....
    db %...XXX..
    db %..XX....
    db %..XX....
    db %XXX.....
    db %........

    db %.XXX.XX.
    db %XX.XXX..
    db %........
    db %........
    db %........
    db %........
    db %........
    db %........

    db %..X.....
    db %..XX....
    db %..XXX...
    db %..XXXX..
    db %..XXXX..
    db %..XXX...
    db %..XX....
    db %..X.....
.end::

section "Dialog Text", rom0

; Text
/*
Intro::
    db "Your day is going pretty great, when", "suddenly.", DELAY, ".", DELAY, NEXT_DIALOG
    db DELAY, ".", DELAY, ".", DELAY, ".", DELAY, "@everyone", SHAKE_SCREEN, DELAY, NEXT_DIALOG
    db "You: What was that?", NEXT_DIALOG
    db DELAY, SHAKE_SCREEN, DELAY, "Oh damn, they're  back aren't they..", NEXT_DIALOG
    db "???: Free distribution of discord nitro for 3 months from steam!!", NEXT_DIALOG
    db "You: Shit.", NEXT_DIALOG
    db "???: https://discord.com/notro", STR_TERM
.end::
*/

OptionDialogQuestion:: db_term_string "Do you like cats?"

OptionDialog::
    init_dialog \ 
        "Mew", DSeq_Test_Handler, \
        "Yes, I love cats.", DSeq_Test_Handler, \
        "I am a bad human.", DSeq_Test_Handler

DialogOptions::
.o1:: db_term_string ":)"
.o2:: db_term_string "Correct answer."
.o3:: db_term_string ">:("

/*
; screen shake test dialog
Intro::
    db NEXT_DIALOG
    rept 18 * 4
    db "A"
    endr
    rept 300
    db SHAKE_SCREEN
    endr
    db STR_TERM
.end::
*/

/*
============================
Variables
============================
*/

section "Variables", wram0
IsStartupFinished:: ds 1
Temp::
    .1:: ds 1
    .2:: ds 1
